---

- name: "SECTION | 1.1 | FileSystem Configurations"
  import_tasks: cis_1.1.1.x.yml
- import_tasks: cis_1.1.x.yml

- name: "SECTION | 1.2 | Configure Software Updates"
  import_tasks: cis_1.2.x.yml

- name: "SECTION | 1.3 | Filesystem Integrity"
  import_tasks: cis_1.3.x.yml
  when: rhel7cis_config_aide

- name: "SECTION | 1.4 | Secure Boot Settings"
  import_tasks: cis_1.4.x.yml

- name: "SECTION | 1.5 | Additional Process Hardening"
  import_tasks: cis_1.5.x.yml

- name: "SECTION | 1.6 | Mandatory Access Control"
  import_tasks: cis_1.6.x.yml
  when: not rhel7cis_selinux_disable

- name: "SECTION | 1.7 | Warning Banners"
  import_tasks: cis_1.7.x.yml

- name: "SECTION | 1.8 | GDM Login"
  import_tasks: cis_1.8.x.yml

- name: "SECTION | 1.9 | Updated and Patches"
  import_tasks: cis_1.9.x.yml

---

- name: "SECTION | 2.1 | inetd Services"
  import_tasks: cis_2.1.x.yml

- name: "SECTION | 2.2.1 | Time Synchronization"
  import_tasks: cis_2.2.1.x.yml

- name: "SECTION | 2.2 | Special Purpose Services"
  import_tasks: cis_2.2.x.yml

- name: "SECTION | 2.3 | Service Clients"
  import_tasks: cis_2.3.x.yml

- name: "SECTION | 2.4 | Nonessential Services"
  import_tasks: cis_2.4.x.yml

---

- name: "SECTION | 3.1 | Disable unused network protocols and devices"
  import_tasks: cis_3.1.x.yml

- name: "SECTION | 3.2 | Network Parameters (Host Only)"
  import_tasks: cis_3.2.x.yml

- name: "SECTION | 3.3 | Network Parameters (Host and Router)"
  import_tasks: cis_3.3.x.yml

- name: "SECTION | 3.4 | Uncommon Network Protocols"
  import_tasks: cis_3.4.x.yml

- name: "SECTION | 3.5.1 | Configure firewalld"
  import_tasks: cis_3.5.1.x.yml
  when:
      - rhel7cis_firewall == "firewalld"
  tags:
      - firewalld

- name: "SECTION | 3.5.2 | Configure nftables"
  import_tasks: cis_3.5.2.x.yml
  when:
      - rhel7cis_firewall == "nftables"
  tags:
      - nftables

- name: "SECTION | 3.5.3.x.x | Configure iptables"
  block:
      - name: "SECTION | 3.5.3.1.x | Configure iptables"
        import_tasks: cis_3.5.3.1.x.yml
      - name: "SECTION | 3.5.3.2.x | Configure iptables"
        import_tasks: cis_3.5.3.2.x.yml
  when:
      - rhel7cis_firewall == "iptables"
  tags:
      - iptables

- name: "SECTION | 3.5.3.3.x | Configure ip6tables"
  import_tasks: cis_3.5.3.3.x.yml
  when:
      - not rhel7cis_ipv6_required
      - rhel7cis_firewall == "iptables"
  tags:
      - iptables
      - ip6tables

---

- name: "SECTION | 4.1| Configure System Accounting (auditd)"
  import_tasks: cis_4.1.1.x.yml

- name: "SECTION | 4.1.2.x| Configure Data Retention"
  import_tasks: cis_4.1.2.x.yml

- name: "SECTION | 4.2.x| Configure Logging"
  import_tasks: cis_4.2.1.x.yml

- name: "SECTION | 4.2.2.x| Configure journald"
  import_tasks: cis_4.2.2.x.yml

- name: "SECTION | 4.2.x | logfile configuration"
  import_tasks: cis_4.2.x.yml

---

- name: "SECTION | 5.1 | Configure time-based job schedulers"
  import_tasks: cis_5.1.x.yml

- name: "SECTION | 5.2 | Configure Sudo"
  import_tasks: cis_5.2.x.yml

- name: "SECTION | 5.3 | Configure SSH Server"
  import_tasks: cis_5.3.x.yml

- name: "SECTION | 5.4 | Configure PAM"
  import_tasks: cis_5.4.x.yml

- name: "SECTION | 5.5.1 | Set Shadow Password Suite Parameters"
  import_tasks: cis_5.5.1.x.yml

- name: "SECTION | 5.5 | User Accounts and Environment"
  import_tasks: cis_5.5.x.yml

- import_tasks: cis_5.6.yml
- import_tasks: cis_5.7.yml

---

- name: "SECTION | 6.1 | System File Permissions"
  import_tasks: cis_6.1.x.yml

- name: "SECTION | 6.2 | User and Group Settings"
  import_tasks: cis_6.2.x.yml

